_target_: src.datamodules.adapt_datamodule.AdaptDataModule

data_dir: ${data_dir}/pyg-format
dataset: cora
split: full

pin_memory: False
num_workers: 15

lr: 0.001
weight_decay: 1e-5
batch_size: 64
undirected: True

# AdaptiveSampler
node_budget: 30
alpha: 0.3
max_hop: 10
max_degree: 16
min_nodes: 70
p_gather: sum
num_groups: 1
group_type: full
ego_mode: False
to_single_layer: False

